### PR TITLE
Make displayed length of string assertions configurable at AssertionScope

### LINKED ISSUE #392: Changing `StringPrintLength` at an `AssertionScope` has no effect
### Description

The `StringPrintLength` is configurable only on a global level (#100).
When changing the value at an `AssertionScope`, its value is ignored.

### Reproduction Steps

```csharp
[Fact]
public void Use_configuration_when_highlighting_string_difference()
{
    // Arrange
    string subject = "this is a very long string with lots of words that most won't be displayed in the error message!";
    string expected = "this is another string that differs after a couple of words.";
    Action action = () => 
    {
        using AssertionScope scope = new();
        scope.FormattingOptions.StringPrintLength = 10;

        subject.Should().Be(expected);
    };        
        
    // Assert
    action.Should().Throw<XunitException>().WithMessage("""
        *
                        ↓ (actual)
            "this is a very long…"
            "this is another…"
                        ↑ (expected).
        """);
}
```

### Expected behavior

The test should succeed

### Actual behavior

The test fails with
```
Expected exception message to match the equivalent of "*
              ↓ (actual)
    "this is a very long…"
    "this is another…"
              ↑ (expected).", but "Expected subject to be the same string, but they differ at index 9:
            ↓ (actual)
  "this is a very long string with lots of words that most…"
  "this is another string that differs after a couple of…"
            ↑ (expected).
" does not.
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

I remember, that this was known, when implementing it in #100, but it still feels like a bug, and not an implementation limitation.

My suggestion would be to attach the formatting options to the `AssertionChain`. This wasn't necessary before, because `StringPringLength` is the only `FormattingOption` which isn't used in an actual `IValueFormatter`, but somewhere else.

```csharp
public class AssertionChain
{
    internal FormattingOptions FormattingOptions => getCurrentScope().FormattingOptions;
}
```

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

### PR DESCRIPTION
**Pull request by cbersch**
Fix #392 

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/main/Tests/AwesomeAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/main/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://awesomeassertions.org/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/main/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/main/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/main/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://awesomeassertions.org/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

## Legal checklist

* [x] This work is entirely original, it is not derived from any existing code incompatible with the Apache 2.0 License, like FluentAssertions.

### CODE REVIEW

File: Src/AwesomeAssertions/Execution/AssertionChain.cs
Comment (lg2de) [inline Src/AwesomeAssertions/Execution/AssertionChain.cs:1]: To see the difference I would like to see different commits for the cleanup you performed and for the real change.

File: Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs [hunk 1]
```diff
@@ -26,6 +26,22 @@ public void When_global_formatting_settings_are_modified()
         AssertionScope.Current.FormattingOptions.StringPrintLength.Should().Be(321);
     }
 
+    [Fact]
+    public void When_scope_formatting_settings_are_modified()
```
Comment (lg2de) [inline Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs]: I'm missing the expectation. (It is missing in the test above too.)

File: docs/_pages/releases.md [hunk 2]
```diff
@@ -11,6 +11,8 @@ sidebar:
 ### Fixes
 * Fix assembly loading for NUnit4 and `LifeCycle.InstancePerTestCase` with Microsoft.Testing.Platform - [#362](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/362)
 
+* Make displayed length of string assertions configurable at `AssertionScope` - [#393](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/393)
```
Comment (lg2de) [inline docs/_pages/releases.md]: I think, from users view the configuration is not newly configurable. But, now it gets working. So:

```suggestion
* Fix configuring displayed length of string assertions at `AssertionScope` - [#393](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/393)
```

File: Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs [hunk 3]
```diff
@@ -26,6 +26,22 @@ public void When_global_formatting_settings_are_modified()
...
+        parent.FormattingOptions.UseLineBreaks = true;
+        parent.FormattingOptions.MaxDepth = 123;
+        parent.FormattingOptions.MaxLines = 33;
+        parent.FormattingOptions.StringPrintLength = 321;
+
+        using AssertionScope nested = new();
+        nested.FormattingOptions.UseLineBreaks.Should().BeTrue();
+        nested.FormattingOptions.MaxDepth.Should().Be(123);
+        nested.FormattingOptions.MaxLines.Should().Be(33);
+        nested.FormattingOptions.StringPrintLength.Should().Be(321);
```
Comment (IT-VBFK) [inline Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs]: For me tests for 
- changing this inside a nested scope and verify it doesn't float outside
- disposing a nested scope and verify it gets reset

are missing (but we could argue if the [other tests](https://github.com/AwesomeAssertions/AwesomeAssertions/blob/main/Tests/AwesomeAssertions.Specs/Execution/AssertionScopeSpecs.ScopedFormatters.cs) for such a scenario are working this will work too 🤔)

Comment (cbersch) [reply Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs]: I removed this test. I thought it would be helpful, but is not directly related to my changes.

File: Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs (hunk 1 above)
Comment (cbersch) [reply Tests/AwesomeAssertions.Specs/Configuration/FormattingOptionsSpecs.cs]: I removed this test. I thought it would be helpful, but is not directly related to my changes.

File: docs/_pages/releases.md [hunk 4]
```diff
@@ -11,6 +11,8 @@ sidebar:
 ### Fixes
 * Fix assembly loading for NUnit4 and `LifeCycle.InstancePerTestCase` with Microsoft.Testing.Platform - [#362](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/362)
 
+* Fix configuring displayed length of string assertions at `AssertionScope` - [#393](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/393)
```
Comment (lg2de) [inline docs/_pages/releases.md:14]:
```suggestion
* Fix configuring displayed length of string assertions at `AssertionScope` - [#393](https://github.com/AwesomeAssertions/AwesomeAssertions/pull/393)
```

File: Tests/AwesomeAssertions.Specs/Formatting/FormatterSpecs.cs [hunk 5]
```diff
@@ -20,27 +21,19 @@ public void Use_configuration_when_highlighting_string_difference()
...
-        }
+            using AssertionScope scope = new();
+            scope.FormattingOptions.StringPrintLength = 10;
+
+            subject.Should().Be(expected);
+        };
+
+        // Assert
+        act.Should().Throw<XunitException>()
+            .WithMessage("""*"this is a very long…"*"this is another…"*""");
```
Comment (IT-VBFK) [inline Tests/AwesomeAssertions.Specs/Formatting/FormatterSpecs.cs:36]: Think we should keep the original raw string here

**Review by IT-VBFK — APPROVED** [review]

File: Tests/AwesomeAssertions.Specs/Formatting/FormatterSpecs.cs (hunk 5 above)
Comment (cbersch) [reply Tests/AwesomeAssertions.Specs/Formatting/FormatterSpecs.cs:36]: Why? This test is only about the shortening of the text, we have plenty of other tests which check the arrow alignment. And the newlines are ignored anyway.
